### ISSUE TITLE
Runefile syntax for multiple inputs and outputs

### ISSUE THREAD

**Issue by Michael-F-Bryan** [hotg-ai/rune#135]
I'm trying to figure out the syntax for a Runefile where each stage might have multiple inputs and multiple outputs, and I was hoping to get some input.

## Example

As an example, let's do some DSP preprocessing which takes data from the `audio` capability and passes it through a `fft `preprocessor. Then on the other side we have samples from the `accelerometer` being passed through a `normalize` step to make the data independent of how far/hard you move the device.

Next we take the outputs from `fft` and `accelerometer` and send them to a `model`. This model sends a list of probabilities to the `label` proc block which then turns it to a UTF-8 string that gets sent to the main `output`.

We've also got a `debug` output which taps into `fft` , `model`, and `label` and you may want to disable independently.

That's a lot of words, but we're essentially trying to construct this pipeline:

![DeepinScreenshot_select-area_20210502174923](https://user-images.githubusercontent.com/17380079/116818026-d498db00-ab9b-11eb-9fcd-bca6d4944628.png)

## Concept 1 - Modified Runefile

One syntax idea is to use `--input some_stage` and `--input-type f32[42]` for declaring a stage's input(s), with the corresponding `--output some_stage` and `--output-type i8[1960]` for specifying the output stage and its type. Under this model you can have multiple inputs but a single output (but that output may be copied to multiple stages). 

This means we'd stop using angle brackets for input/output types because I think it'd be hard to adapt the `PROC_BLOCK<input_type, output_type>` syntax to multiple inputs/outputs without it being ugly or turning into punctuation soup (e.g. `PROC_BLOCK<(i32[1920, 1080], f32[128, 3]), f32[4]> model ...`).

```
FROM runicos/base

CAPABILITY audio SOUND --hz 16000 --output-type I16[16000]
CAPABILITY accelerometer ACCEL -n 128 --output-type F32[128, 3]

PROC_BLOCK fft hotg-ai/rune#proc_blocks/fft \
    --input audio --input-type I16[16000] \
    --output-type I8[1960]
PROC_BLOCK normalize hotg-ai/rune#proc_blocks/normalize \
    --input accelerometer --input-type f32[128, 3] \
    --output-type f32[128, 3]
MODEL model ./model.tflite --input audio \
    --input fft \
    --input normalize --input-type f32[128, 3] \
    --output-type f32[4]
PROC_BLOCK label hotg-ai/rune#proc_blocks/ohv_label \
    --labels=Wing,Ring,Slope,Unknown \
    --input model \
    --output-type UTF8

OUT output SERIAL --input fft --input model --input label
OUT debug SERIAL --input label
```

That would be a relatively minor change to the language syntax and probably take a couple hours of fiddling in the parser. Unfortunately it makes a Runefile context sensitive (a --input-type argument can only follow an --input and some arguments are only specific to certain commands) which isn't nice from a language design standpoint.

## Concept 2 - Lua

Alternatively, instead of writing our own DSL we could leverage an existing one (e.g. Lua with our own custom functions):

```lua
audio = capability {
    kind = "SOUND",
    output_type = i16(16000),
    args = { hz = 16000 },
}

accelerometer = capability { kind = "ACCEL", output_type = f32(128, 3) }

normalize = proc_block {
    source = "hotg-ai/rune#proc_blocks/normalize",
    input = accelerometer,
    output_type = f32(128, 3),
}

model = model {
    filename = "./model.tflite",
    input = { audio, accelerometer },
    output_type = f32(4),
}

label = proc_block {
    source = "hotg-ai/rune#proc_blocks/ohv_label",
    input = model,
    output_type = utf8,
    args = {
        labels = { "Wing", "Ring", "Slope", "Unknown" },
    },
}

output = out { kind = "SERIAL", input = { label } }
debug = out { kind = "SERIAL", input = { fft, model, label } }
```

I'd maybe consider the above for a Runefile v3 seeing as it's quite a large change.

**Comment by Michael-F-Bryan** [comment]
## Concept 3 - YAML

```yaml
image: "runicos/base"

pipeline:
  audio:
    capability: SOUND
    outputs:
    - type: i16
      dimensions: [16000]
    args:
      hz: 16000

  accelerometer:
    capability: ACCEL
    outputs:
    - type: f32
      dimensions: [128, 3]

  normalize:
    proc-block: "hotg-ai/rune#proc_blocks/normalize"
    inputs:
    - accelerometer
    outputs:
    - type: f32
      dimensions: [128, 3]

  model:
    model: "./model.tflite"
    inputs:
    - audio
    - accelerometer
    outputs:
    - type: f32
      dimensions: [4]

  label:
    proc-block: "hotg-ai/rune#proc_blocks/ohv_label"
    inputs:
    - model
    outputs:
    - type: utf8
    args:
      labels: ["Wing", "Ring", "Slope", "Unknown"]

  output:
    out: SERIAL
    inputs:
    - label

  debug:
    out: SERIAL
    inputs:
    - fft
    - model
    - label
```
