### ISSUE TITLE
Need simple procbloc that converts u8s to f32

### ISSUE THREAD

**Issue by Ge-te** [hotg-ai/rune#220]
tf.js models are mostly unquantised, but RGB input is, to make runevm.js generic for images, we need a simple procbloc like this:
PROC_BLOCK<U8[3, 224, 224], F32[3, 224, 224]> un-quantise hotg-ai/rune#proc_blocks/un-quantise

just converting all u8 ints into f32 floats like f32 = u8/255

**Comment by Michael-F-Bryan** [comment]
This ties into something @Mi1ind ran into a while ago. Basically, we'll spend a bunch of time "casting" between tensors of different types where the tensor's contents don't really change value (e.g. `10_u32` goes to `10.0`). 

@kthakore, at the moment we're handling this in a fairly ad-hoc fashion (make a new proc blok for every cast), but in the long run we should come up with a better/more general/builtin way of doing it.

**Comment by Mi1ind** [comment]
@Ge-te tested this out - We can use the existing image-normalization proc_block. Setting `mean = 0.0`, `standard deviation = 255.0` would normalize `u8` to `f32` ([0,1]).

`Runefile.yml` for the proc_block would look like this:
```yaml
normalize:
    proc-block: "hotg-ai/rune#proc_blocks/image-normalization"
    inputs:
      - image
    outputs:
      - type: F32
        dimensions:
          - 3
          - 224
          - 224
    args:
      rgb:
        - 0.0
        - 255.0
```
