### ISSUE TITLE
Arguments in a runefile should just be plain strings

### ISSUE THREAD

**Issue by Michael-F-Bryan** [hotg-ai/rune#237]
In the YAML format, arguments provided to capabilities have the type [`rune_core::Value`](https://github.com/hotg-ai/rune/blob/dad6dd2a5d54e180f9dfca13736d1f94b113c559/crates/rune-core/src/value.rs#L3-L13), which forces both ends to `match` on the specified type and figure out how to interpret the bytes it has been provided. 

This is actually a massive pain because to set parameters and such you still need to [coerce the values to the correct type](https://github.com/hotg-ai/rune/blob/dad6dd2a5d54e180f9dfca13736d1f94b113c559/crates/rune-cli/src/run/sound.rs#L148-L150).

Let's update the Rune-Runtime interface so [`request_capability_set_param()`](https://github.com/hotg-ai/rune/blob/dad6dd2a5d54e180f9dfca13736d1f94b113c559/images/runicos-base/wasm/src/intrinsics.rs#L119-L126) and friends just take strings as values.

**Comment by Michael-F-Bryan** [comment]
One way we can work with lists is by using YAML's block strings.

```yaml
pipeline:
  my-proc-block:
    proc-block: "..."
    args:
      word-list: |
        this
        is
        a
        word
        list
    other-arg: 42
```
