### ISSUE TITLE
Let users use a shorthand for types in their Runefiles

### ISSUE THREAD

**Issue by Michael-F-Bryan** [hotg-ai/rune#250]
Each step in a Rune needs to explicitly mention the type of its outputs.

```yaml
pipeline:
  content_image:
    capability: IMAGE
    outputs:
    - type: u8
      dimensions: [1, 384, 384, 3]
```

However, using a dict with `type` and `dimensions` keys can get a bit verbose (even when you write the list as `[1, 384, 384, 3]` instead of the normal bullet-point notation).

As an alternative, it'd be nice to use a shorthand.

```yaml
pipeline:
  content_image:
    capability: IMAGE
    outputs:
    - type: u8[1, 384, 384, 3]
```

This could be implemented in a backwards compatible way by switching [the `Type` struct](https://github.com/hotg-ai/rune/blob/35c516c54bfd0024cbd0d371abe2a1296ba04dd1/crates/syntax/src/yaml/types.rs#L297-L302) to an untagged enum (in `serde` parlance).

CC: @kthakore

**Comment by f0rodo** [comment]
I think we also need a `types` field

```
types:
    $image_raw_type: u8[255, 3]

...

   outputs: $image_raw_type
```

Something like that
