### ISSUE TITLE
data did not match any variant of untagged enum Stage

### ISSUE THREAD

**Issue by Mohit0928** [hotg-ai/rune#294]
I wrote yml file for [YAMNet ](https://tfhub.dev/google/lite-model/yamnet/tflite/1) (a deep net that predicts 521 audio events), but it is throwing this error.
```
Error: Unable to parse the Runefile

Caused by:
    data did not match any variant of untagged enum Stage
```
Model info:
```
Inputs:
        waveform: Float32[1]
Outputs:
        Identity: Float32[1, 521]
        Identity_1: Float32[1, 1024]
        Identity_2: Float32[1, 64]
```
Input: We can pass any variable size audio file as input. To keep it simple, I have decided to pass only 1-sec audio as input.
Outputs: There will be 3 outputs. I only need 1st for my use case.
Below is the .yml file that I wrote for this.
```
version: 1
image: runicos/base

pipeline:
  audio:
    capability: SOUND
    outputs:
      - type: F32
        dimensions: [1,16000]
    args:
      hz: 16000
      sample_duration_ms: 1000
  yamnet:
    model: "./model.tflite"
    inputs:
      - audio
    outputs:
      - type: F32
        dimensions: [1,521]
      - type: F32
        dimensions: [1,1024]
      - type: F32
        dimensions: [1,64]
  most_confident_index:
    proc-block: "hotg-ai/rune#proc-blocks/most_confident_indices"
    inputs:
      - yamnet.0
    outputs:
      - type: U32
        dimensions: [3]
    args:
      count: 3
  label:
    inputs:
      - most_confident_index
    outputs:
      - type: UTF8
        dimensions: [3]
    args:
      labels:
        -  Speech
        -  Child speech, kid speaking
        -  Conversation
        -  Narration, monologue
        -  Babbling
        -  Speech synthesizer
     .......
  serial:
    out: SERIAL
    inputs:
      - label
```
