### ISSUE TITLE
Need a proc-block to get a single output from a multiple output streams

### ISSUE THREAD

**Issue by Mohit0928** [hotg-ai/rune#295]
```
version: 1
image: runicos/base

pipeline:
  audio:
    capability: SOUND
    outputs:
      - type: F32
        dimensions: [1,16000]
    args:
      hz: 16000
      sample_duration_ms: 1000
  yamnet:
    model: "./model.tflite"
    inputs:
      - audio
    outputs:
      - type: F32
        dimensions: [1,521]
      - type: F32
        dimensions: [1,1024]
      - type: F32
        dimensions: [1,64]
  most_confident_index:
    proc-block: "hotg-ai/rune#proc-blocks/most_confident_indices"
    inputs:
      - yamnet.0
    outputs:
      - type: U32
        dimensions: [3]
    args:
      count: 3
  label:
    inputs:
      - most_confident_index
    outputs:
      - type: UTF8
        dimensions: [3]
    args:
      labels:
        -  Speech
        -  Child speech, kid speaking
        -  Conversation
        -  Narration, monologue
        -  Babbling
        -  Speech synthesizer
     .......
  serial:
    out: SERIAL
    inputs:
      - label
```
In the above yml file, I want to use only the 1st output of "yamnet" as input to the "most_confident_index". We will need a proc-block that could get a single output from multiple output streams.
