### ISSUE TITLE
Improve error message when input isn't declared in pipeline

### ISSUE THREAD

**Issue by Mokshit06** [hotg-ai/rune#319]
Currently, if you have a Runefile.yml that looks like
```yaml
pipeline:
  some_input:
    capability: ...
    output: ...
  processing:
    inputs:
      - another_input
```
it will throw an error like `IndexMap: key not found` because `another_input` isn't declared in the pipeline.

I think it would be a better debugging experience if it would throw an error like `'another_input' was not found in the pipeline, but is being passed as an input to 'processing'`.
This error is particularly confusing when it occurs due to a typo.
