### ISSUE TITLE
Runefile.yml not checking input/output type and dimensions

### ISSUE THREAD

**Issue by Mohit0928** [hotg-ai/rune#330]
I'm typing the wrong input/output type and dimensions in the `Runefile.yml`, but even then, it's building a `rune`. @Michael-F-Bryan, It should throw an error if I write a wrong input/output type and dimension in the Runefile.yml. Below is an example:

Model info:
```
Inputs:
        serving_default_input:0: f32[1,192,192,3]
Outputs:
        StatefulPartitionedCall:0: f32[1,1,17,3]
```

Typing a wrong Runefile.yml:
```
version: 1
image: runicos/base

pipeline:
  image:
    capability: IMAGE
    outputs:
      - type: u8
        dimensions: [1,192,192,3]
    args:
      height: 192
      width: 192
      pixel-format: "@PixelFormat::RGB"
  normalizer:
    proc-block: "hotg-ai/rune#proc-blocks/image-normalization"
    inputs:
      - image
    outputs:
      - type: f32
        dimensions: [1,191,191,3]  #wrong output dimensions, it should be [1,192,192,3]
  pose:
    model: "./movenet_singlepose_lightning_3.tflite"
    inputs:
      - normalizer
    outputs:
      - type: u32             #wrong output type, it should be f32
        dimensions: [1,17,17,3]
  serial:
    out: SERIAL
    inputs:
      - pose
```
